<script>
import Header from '../components/Header.vue'
export default {
    components: {
        Header
    }
}
</script>


<template>
        <header class="HomeHeader">
        <h2>Home</h2>
    </header>
    <body>
        <div class= "home-body">
            <br>
            <p>Explain what FindersKeepers is</p>
            <br>
            <p>Explain how to use it</p>
            <br>
            <p>Explain limitations</p>
            <br>
        </div>
    </body>
</template>


<style>
.home-body{
    font-family: Arial, Helvetica, sans-serif;
}
</style>